language: python
matrix:
  include:
    # Python version is just for the look on travis.
    - python: 2.7
      env: TOXENV=flake8

    - python: 2.7
      env: TOXENV=sphinx

    - python: 2.7
      env: TOXENV=readme

    - python: 2.7
      env: TOXENV=py27

    - python: 3.4
      env: TOXENV=py34

    - python: 3.5
      env: TOXENV=py35

install:
  - make develop

script:
  - make test
